### ISSUE TITLE
Can't save certain types

### ISSUE THREAD

**Issue by nilsweb** [IF11I/backend#15]
I get the following response when trying to save a component type:

```
PHP Warning:  json_decode() expects parameter 1 to be string, array given in /backend/src/routes/routes.php on line 688
PHP Warning:  Invalid argument supplied for foreach() in /backend/src/routes/routes.php on line 690
```

Please fix this and provide an error message instead when things go wrong! ;)

**Comment by nilsweb** [comment]
This also seems to happen with components... Not sure if I'm doing something wrong... :p

**Comment by weinzierl-florian** [comment]
this happens if you don't provide an array of attributes whether to a component type or a component
If you don't want attributes you should provide an empty array
![2018_07_25_20_06_24_backend_c_xampp_htdocs_projekt_backend_ _src_routes_routes php_backend_](https://user-images.githubusercontent.com/10184013/43219035-78eec3c8-9046-11e8-8a91-696c4ad33d7e.jpg)

**Comment by nilsweb** [comment]
I'll look into it again. Maybe the array didn't get initialized properly on the frontend side?

**Comment by nilsweb** [comment]
I'm sending the following body:
``` json
{
	"name": "Computer",
	"attributes": [
		{
			"id": "1"
		}
	]
}
```

Did you run something similar to `$componentTypeData = json_decode(_____);` before the statement you highlighted in your screenshot?
